language: haskell

# notifications:
#   email:
#     - pxqr.sta@gmail.com

ghc:
  - "8.2"
  - "8.0"
  - "7.10"
  - "7.8"

install:
  cabal install --only-dependencies --enable-tests

script:
  cabal configure && cabal build && cabal test
